export const questions = [
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'Explain the Virtual DOM in React and how it improves performance.',
    hint: 'Talk about diffing, reconciliation, and selective DOM updates.',
    answer: 'The Virtual DOM is an in-memory representation of the UI. React compares new and previous trees, computes the minimal changes, and updates the real DOM efficiently.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'wipro'],
    question: 'What is middleware in Express.js? Give a real-world use case.',
    hint: 'Think about authentication, logging, validation, and error handling.',
    answer: 'Middleware is a function that runs during the request-response cycle. It can inspect or modify req/res, end the response, or call next().',
  },
  {
    role: 'mern',
    topic: 'Auth',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How does JWT authentication work? Explain the full flow.',
    hint: 'Cover token creation, signing, storage, sending, and verification.',
    answer: 'After login, the server signs a token containing user claims. The client sends it in Authorization headers. Protected routes verify the signature before granting access.',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Easy',
    companies: ['cognizant', 'tcs', 'wipro'],
    question: 'What is the difference between SQL and NoSQL? When would you choose MongoDB?',
    hint: 'Compare schema design, joins, document shape, and scaling.',
    answer: 'SQL is relational and schema-first. MongoDB stores flexible JSON-like documents and is useful when data shape evolves quickly or maps naturally to documents.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Explain useEffect cleanup function with an example.',
    hint: 'Think about subscriptions, timers, and event listeners.',
    answer: 'A cleanup function runs before an effect re-runs or the component unmounts. It prevents leaks by clearing intervals, aborting requests, or removing listeners.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks', 'infosys'],
    question: 'Explain the event loop in Node.js.',
    hint: 'Mention call stack, microtasks, timers, poll, and callbacks.',
    answer: 'The event loop lets Node handle async work without blocking. It processes phases like timers, poll, and check, while microtasks run between phases.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'What is Redux and when should you use it over Context API?',
    hint: 'Consider app scale, complexity, devtools, and performance.',
    answer: 'Redux centralizes state with predictable updates. Use it for large apps with complex shared state; Context API suits simpler prop-drilling cases.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'wipro', 'infosys'],
    question: 'How do you handle CORS in a Node.js/Express backend?',
    hint: 'Mention the cors npm package and manual headers.',
    answer: 'Use the cors middleware or set Access-Control-Allow-Origin headers to permit cross-origin requests from trusted frontend origins.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Easy',
    companies: ['zoho', 'tcs', 'amazon'],
    question: 'Find the middle element of a Linked List.',
    hint: 'Use the fast and slow pointer (Tortoise and Hare) approach.',
    practiceUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    answer: 'Use two pointers. Fast moves two steps, Slow moves one. When Fast reaches the end, Slow is at the middle.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Medium',
    companies: ['amazon', 'freshworks', 'zoho'],
    question: 'Implement a Stack using Queues.',
    hint: 'You can use two queues or one queue with rotation.',
    practiceUrl: 'https://leetcode.com/problems/implement-stack-using-queues/',
    answer: 'Can be done using two queues by making push operation costly or pop operation costly.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Hard',
    companies: ['amazon', 'zoho'],
    question: 'Lowest Common Ancestor of a Binary Tree.',
    hint: 'Use recursion: if current node is one of the targets, it could be LCA.',
    practiceUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
    answer: 'Recurse left and right. If both return non-null, current node is LCA. If one is null, return the other.',
  },
  {
    role: 'hr',
    topic: 'Introduction',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Tell me about yourself.',
    hint: 'Keep it around 90 seconds: education, skills, projects, and role fit.',
    answer: 'A strong fresher answer connects education, technical skills, projects, and why the target role is a good fit.',
  },
  {
    role: 'hr',
    topic: 'Motivation',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'cognizant', 'wipro'],
    question: 'Why do you want to join this company?',
    hint: 'Research the company. Mention specific product, values, and growth.',
    answer: 'Connect your skills and goals with the company mission, culture, and learning opportunities.',
  },
  {
    role: 'hr',
    topic: 'Behavioral',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'Describe a challenging project and how you handled it.',
    hint: 'Use STAR: Situation, Task, Action, Result.',
    answer: 'Use a structured story with the problem, your responsibility, actions, trade-offs, and measurable result.',
  },
  {
    role: 'hr',
    topic: 'Career Goals',
    difficulty: 'Medium',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'Where do you see yourself in 5 years?',
    hint: 'Show ambition and alignment with the company trajectory.',
    answer: 'Describe growth in technical depth, ownership, and contribution to team or product outcomes.',
  },
];
