export const questions = [
  // ================= REACT.JS CORE & ADVANCED (QUESTIONS 1–40) =================
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'What is the Virtual DOM, and how does React reconcile changes efficiently using the diffing algorithm?',
    hint: 'Talk about O(n) heuristic reconciliation, elements typing, and key props.',
    answer: 'The Virtual DOM is a lightweight JS representation of the real DOM. Instead of updating the DOM on every change, React updates the virtual tree, diffs it against the previous state using an O(n) heuristic algorithm, and batches minimal updates (reconciliation).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'infosys'],
    question: 'Explain the difference between functional components with Hooks and class-based components.',
    hint: 'Compare stateful logic sharing, lifecycle hooks vs class syntax, and boilerplate.',
    answer: 'Class components use ES6 classes, manage state using this.state, and use lifecycle methods. Functional components are simpler JS functions using Hooks (useState, useEffect) for state and side-effects, promoting better reusability and less boilerplate.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What are the rules of Hooks, and why must they be called at the top level of a component?',
    hint: 'Hooks rely on call order consistency across renders.',
    answer: 'Rules: 1) Call Hooks only at the top level (never in loops, conditions, or nested functions). 2) Call Hooks only from React function components or custom Hooks. This guarantees Hooks run in the exact same order on every render, keeping state aligned.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'How does the useEffect dependency array work, and how do you implement a clean-up function to prevent memory leaks?',
    hint: 'Subscriptions, event listeners, and timer cleanups.',
    answer: 'The dependency array controls effect execution: empty [] runs once on mount; variables run on change; no array runs on every render. Returning a function executes cleanup before the next effect run or unmount, removing event listeners/timers.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['wipro', 'infosys', 'tcs'],
    question: 'Explain the concept of lifting state up and one-way data binding in React.',
    hint: 'Passing state ownership to a common parent.',
    answer: 'React uses one-way data binding (flows down from parent to child via props). Lifting state up involves moving shared state to the closest common ancestor of components that need it, passing setters down as callbacks.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'What is the difference between useMemo and useCallback? Provide specific code use cases.',
    hint: 'useMemo caches computation output; useCallback caches function definitions.',
    answer: 'useMemo returns a memoized value of a calculation. useCallback returns a memoized callback function itself. Use useMemo to avoid expensive calculations on re-render. Use useCallback to prevent unnecessary renders of child components taking function props.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How does the Context API work, and in what scenarios should you prefer it over dedicated state managers like Redux?',
    hint: 'Consider low-frequency theme settings vs high-frequency global states.',
    answer: 'Context API shares data (like theme or auth) globally without prop drilling. Use Context for simple, low-frequency updates. For complex global states, high-frequency actions, or advanced debugging, Redux is preferred due to rendering optimizations.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What is Prop Drilling, and what are the primary architectural ways to avoid it?',
    hint: 'Passing data down deep nesting chains. Context or state centralization.',
    answer: 'Prop drilling is passing props through intermediate components that do not need them, just to reach a deep child. Avoid it using the Context API, state management libraries (Redux, Zustand), or by utilizing component composition (passing components as props).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks'],
    question: 'Explain React fiber architecture and how it enables asynchronous, concurrent rendering capabilities.',
    hint: 'Think scheduling, incremental rendering, and work division units (fibers).',
    answer: 'React Fiber is a re-implementation of React\'s core reconciliation engine. It breaks rendering work into incremental units (fibers) and allows pauses, prioritizations, or aborts of work, enabling Concurrent Mode features like transitions.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant'],
    question: 'What are controlled vs. uncontrolled components, and when would you use a useRef hook?',
    hint: 'State bindings vs direct DOM references.',
    answer: 'Controlled components have their value managed by React state. Uncontrolled components let the DOM store data, accessed via ref. Use useRef when you need direct DOM access (focus, media play) or to persist values without re-rendering.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'How do you handle error boundaries in React, and can they catch errors within asynchronous code or event handlers?',
    hint: 'Class components using componentDidCatch/getDerivedStateFromError.',
    answer: 'Error boundaries are class components implementing getDerivedStateFromError or componentDidCatch. They catch runtime errors in their child tree, but cannot catch errors in async code (like setTimeout), event handlers, or SSR.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'What are React Server Components (RSC), and how do they differ fundamentally from Client Components?',
    hint: 'Server-side rendering, zero client-side bundle impact, database access.',
    answer: 'RSCs render purely on the server, have direct database access, and do not ship JS bundles to the client. Client Components are loaded with client-side JavaScript, allow hooks (useState, useEffect), and support user interactions.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'infosys', 'wipro'],
    question: 'Explain the React component lifecycle methods in class components and map them to equivalent useEffect hooks.',
    hint: 'componentDidMount, componentDidUpdate, componentWillUnmount.',
    answer: 'componentDidMount maps to useEffect(fn, []). componentDidUpdate maps to useEffect(fn, [deps]). componentWillUnmount maps to the function returned by the effect (cleanup).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'cognizant', 'wipro'],
    question: 'Why is the key prop necessary in dynamic lists, and what happens under the hood if you use an index as a key?',
    hint: 'Identity tracking, reconciliation matching, list item shifts.',
    answer: 'Keys help React identify which items have changed, been added, or been removed. Using array indices as keys can cause rendering bugs and state issues if list items are sorted, deleted, or inserted dynamically.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What are High-Order Components (HOCs) and Custom Hooks? Compare their reusability patterns.',
    hint: 'UI/Props wrapping vs state/logic extraction.',
    answer: 'An HOC is a function taking a component and returning a new component, wrapping UI/props behavior. Custom Hooks are functions extracting pure stateful logic. Custom Hooks are preferred since they do not introduce wrapper depth.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'cognizant', 'infosys'],
    question: 'How does React handle synthetic events, and what is the advantage over native browser event handling?',
    hint: 'Cross-browser wrapper, event pooling/delegation.',
    answer: 'React wraps native events in a SyntheticEvent object for cross-browser consistency. It uses event delegation, attaching a single listener at the root rather than individual elements, saving memory.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain the concept of Lazy Loading using React.lazy and Suspense for code-splitting.',
    hint: 'Dynamic imports, chunk bundles on-demand.',
    answer: 'React.lazy dynamically imports components when needed. Wrapped in Suspense (which takes a fallback UI), it loads chunks only when rendered, minimizing primary JS bundles.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'What is the purpose of useReducer, and how does it implement the Redux-like state management pattern?',
    hint: 'Actions, state, reducer function, dispatcher.',
    answer: 'useReducer manages complex local component state. It accepts a reducer function (state, action) and returns current state and a dispatch function, matching Redux patterns.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'How do you optimize a React application that suffers from excessive re-renders due to parent state updates?',
    hint: 'React.memo, custom hook extraction, useCallback caching.',
    answer: '1) Wrap child components in React.memo. 2) Cache callback props with useCallback. 3) Cache objects/arrays passed as props with useMemo. 4) Centralize state or pass components as children.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro'],
    question: 'Explain the difference between Shadow DOM and Virtual DOM.',
    hint: 'Browser encapsulation vs React performance reconciliation.',
    answer: 'Shadow DOM is a native browser API used for scoping styles/markup in Web Components (capsules). Virtual DOM is a React-specific lightweight copy of the real DOM used for reconciliation performance.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'cognizant'],
    question: 'What is StrictMode in React, and what runtime behaviors does it introduce in development environments?',
    hint: 'Double execution of renders/effects, highlighting deprecated APIs.',
    answer: 'StrictMode is a wrapper utility. In development, it intentionally double-invokes renders, lifecycles, and effects to catch side-effects, cleanup leaks, and highlight deprecated APIs.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'How do you safely integrate third-party non-React DOM manipulation libraries with React components?',
    hint: 'useRef to block React DOM updates, useEffect for library initialization.',
    answer: 'Provide an empty div with a useRef. Initialize the library inside useEffect pointing to the ref element. Ensure React never updates this DOM node by avoiding reactive state changes to it.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['freshworks', 'zoho'],
    question: 'Explain the concept of portal elements using ReactDOM.createPortal and its typical use cases.',
    hint: 'Rendering outside parent DOM tree hierarchies.',
    answer: 'Portals render children into a DOM node outside the parent component tree hierarchy. Typical use cases include modals, tooltips, and dropdown panels to avoid overflow/z-index issues.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What is the difference between useState functional updates (e.g., prev => prev + 1) and standard updates?',
    hint: 'Batching schedules and access to latest queue states.',
    answer: 'Standard updates scheduler uses state from the current render closure. Functional updates take a callback receiving the latest queued state, ensuring updates are correct when batching.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How do you handle client-side routing in React using React Router? Explain dynamic route matching and route guards.',
    hint: 'Router context, Link paths, authentication checks.',
    answer: 'React Router intercepts URL changes to swap rendering paths without reloading. Dynamic routes use params (e.g. :id). Guards check conditions (like login status) and navigate away if unauthorized.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'cognizant'],
    question: 'What are the standard strategies to protect specific private routes from unauthorized access in React?',
    hint: 'Wrapper guard components checking auth states.',
    answer: 'Wrap private Route paths in a custom ProtectedRoute component that checks client auth states (e.g. token check). Redirect unauthenticated users using Navigate to a login path.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks'],
    question: 'How does the useImperativeHandle hook work when combined with forwardRef?',
    hint: 'Exposing custom parent handles, DOM ref overrides.',
    answer: 'useImperativeHandle customizes the ref instance exposed to a parent component. Combined with forwardRef, it lets child components restrict parent DOM control to selected methods.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'Explain how to implement custom performance monitoring inside React using the Profiler API.',
    hint: 'Profiler callback props logging render metadata.',
    answer: 'Wrap components in <Profiler id="name" onRender={callback}>. The callback logs the component, phase (mount/update), duration, and reasons for re-rendering.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'What is hydration in SSR (Server-Side Rendering), and why do mismatch errors occur between server and client?',
    hint: 'Attaching listeners to static HTML, client-server layout sync.',
    answer: 'Hydration is the process where React attaches event listeners to pre-rendered server HTML. Mismatch errors occur if client markup differs from server HTML (e.g. using random numbers).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'How do you handle global state operations in Redux Toolkit using slices, actions, and reducers?',
    hint: 'createSlice abstraction, Immer immutable updates.',
    answer: 'Redux Toolkit uses createSlice to define state, actions, and reducers in one block. Under the hood, createSlice uses Immer, allowing developers to write direct mutations.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'What is the purpose of middleware like Redux Thunk or Redux Saga in managing async state side-effects?',
    hint: 'Intercepting dispatches for API queries, promise resolving.',
    answer: 'Redux dispatches are synchronous. Middleware (Thunk, Saga) intercepts dispatches to run async tasks (API calls), dispatching standard success/error actions when resolved.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'How do you execute integration testing of a React component using React Testing Library and Jest?',
    hint: 'User interactions simulation, container render querying.',
    answer: 'React Testing Library renders components and queries their content like a user (getByRole, findByText). Jest provides testing runners and assertions (toBeInTheDocument).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'Explain the differences between SSR, SSG, and ISR patterns in Next.js.',
    hint: 'Dynamic rendering, build-time compilation, incremental cache updates.',
    answer: 'SSR compiles HTML on every request. SSG compiles static HTML at build-time. ISR updates static pages dynamically in the background after generation.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How do you manage cross-origin resource sharing (CORS) configurations from a React frontend perspective?',
    hint: 'Local dev proxy configurations, cross-origin fetch setup.',
    answer: 'Configure a proxy in vite.config.js / package.json to forward requests, avoiding browser blocks. In production, configure CORS response headers on the backend.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What is CSS-in-JS (e.g. Styled Components), and what are its pros and cons relative to standard CSS modules?',
    hint: 'Inline component-level styles, runtime bundle overrides.',
    answer: 'Pros: dynamic scoping, component-level themes. Cons: runtime performance cost, increased JS bundle size. CSS Modules are compiled to static CSS with zero runtime overhead.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain how React handles batching of multiple state updates inside event handlers vs asynchronous callbacks.',
    hint: 'Updates consolidation to minimize renders (React 18 automatic batching).',
    answer: 'React batches state updates to prevent multiple renders. In React 18, automatic batching applies to both event handlers and async callbacks (promises, setTimeout).',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What are the implications of passing inline objects or arrow functions as props to child components?',
    hint: 'Reference values, prop checks, unnecessary rendering loops.',
    answer: 'Inline objects ({}) and arrow functions (() => {}) are recreated on every render. This changes prop references, causing memoized children to re-render anyway.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How do you manage form state validation cleanly using libraries like Formik or React Hook Form with Yup?',
    hint: 'Registered ref fields, form controller models, schema validities.',
    answer: 'React Hook Form hooks component refs to track inputs. Combined with Yup schemas, it runs validation schemas dynamically and provides error states without manual checks.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Easy',
    companies: ['freshworks', 'zoho'],
    question: 'Explain how to build a custom hook to detect window size or check online/offline network connectivity.',
    hint: 'Window resize / online event listeners inside useEffect.',
    answer: 'Inside a custom hook, use useState to track state and useEffect to bind resize / online/offline listeners. Return state and remove listeners on cleanup.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks'],
    question: 'What is the significance of the useLayoutEffect hook, and how does it differ from the standard useEffect hook?',
    hint: 'Synchronous execution before browser paint, layout measurements.',
    answer: 'useEffect runs asynchronously after paint. useLayoutEffect runs synchronously after DOM mutations but before paint. Use it to measure layouts or prevent flickers.',
  },

  // ================= NODE.JS & EVENT LOOP (QUESTIONS 41–75) =================
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'Explain the architecture of Node.js. How does it handle highly concurrent requests despite being single-threaded?',
    hint: 'Think about non-blocking I/O, event loop, and Libuv thread pool.',
    answer: 'Node.js uses a single-threaded event loop to handle execution, but delegates asynchronous tasks (file system, network) to Libuv. Libuv handles operations asynchronously via OS kernels or a helper thread pool, notifying the loop upon completion.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks', 'infosys'],
    question: 'Describe the phases of the Node.js Event Loop in detail.',
    hint: 'Mention Timers, Pending Callbacks, Poll, Check, and Close Callbacks.',
    answer: 'Phases: 1) Timers: executes setTimeout/setInterval callbacks. 2) Pending Callbacks: runs I/O callbacks deferred from previous cycles. 3) Idle/Prepare. 4) Poll: retrieves new I/O events. 5) Check: executes setImmediate callbacks. 6) Close Callbacks (e.g. socket.on("close")).',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Medium',
    companies: ['zoho', 'cognizant'],
    question: 'What is the difference between process.nextTick() and setImmediate()? Which executes first?',
    hint: 'Compare microtask queue execution vs event loop phases.',
    answer: 'process.nextTick() executes immediately after the current operation finishes, before the event loop continues to its next phase. setImmediate() schedules execution in the "Check" phase. process.nextTick() always runs first.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Medium',
    companies: ['freshworks', 'tcs', 'wipro'],
    question: 'What are Streams in Node.js? Differentiate between Readable, Writable, Duplex, and Transform streams.',
    hint: 'Streams handle chunk-by-chunk data processing.',
    answer: 'Streams read/write data sequentially. Types: 1) Readable (e.g. fs.createReadStream). 2) Writable (e.g. fs.createWriteStream). 3) Duplex: both readable and writable (e.g. TCP sockets). 4) Transform: modifies data as it passes through (e.g. zlib compression).',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['infosys', 'tcs'],
    question: 'What is the purpose of the Buffer class in Node.js, and how does it store binary data outside the V8 heap?',
    hint: 'Think about raw binary streams and filesystem memory layout.',
    answer: 'Buffers represent fixed-length sequences of bytes, allocated outside the V8 heap memory. They are used for raw binary data processing (file systems, networks) where JavaScript strings would be inefficient.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro'],
    question: 'What is the role of package-lock.json, and how does it guarantee deterministic, reproducible builds?',
    hint: 'Think about exact dependency versions and transitive trees.',
    answer: 'package-lock.json records the exact version of every package and sub-dependency installed in the dependency tree. This ensures that every developer and production environment installs the identical versions, preventing semantic version drift.',
  },

  // ================= EXPRESS.JS REST APIS (QUESTIONS 76–110) =================
  {
    role: 'mern',
    topic: 'Express',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What is Express.js middleware, and how does the request-response cycle flow through multiple middleware blocks?',
    hint: 'Middleware operates between receiving requests and sending responses.',
    answer: 'Middleware functions have access to req, res, and the next() function. They execute sequentially. If a middleware does not call next() or send a response, the request is left hanging.',
  },
  {
    role: 'mern',
    topic: 'Express',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'How do you implement centralized, structured global error-handling middleware in an Express.js application?',
    hint: 'Express error-handling middleware requires a specific signature with 4 arguments.',
    answer: 'Create a middleware with four parameters: (err, req, res, next). Express detects this signature and routes uncaught errors here. Send a structured JSON response to avoid leaking stack traces.',
  },
  {
    role: 'mern',
    topic: 'Express',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'Explain the step-by-step process of designing JWT (JSON Web Token) authentication and token verification middleware.',
    hint: 'Header inspection, signature verification, and attaching payload.',
    answer: '1) Extract token from Authorization header (Bearer schema). 2) Use jwt.verify() to validate signature against secret. 3) If invalid, return 401/403. 4) If valid, attach decoded payload to req.user and call next().',
  },
  {
    role: 'mern',
    topic: 'Express',
    difficulty: 'Medium',
    companies: ['tcs', 'cognizant', 'wipro'],
    question: 'What is the difference between Session-based authentication vs Token-based authentication strategies in Express?',
    hint: 'Compare stateful storage on server vs stateless verification.',
    answer: 'Session-based is stateful; user data is stored on server (e.g. in Redis) and linked via cookie ID. Token-based (JWT) is stateless; user details are encoded in a signed token stored client-side. Tokens scale better but are harder to revoke.',
  },
  {
    role: 'mern',
    topic: 'Express',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys'],
    question: 'What is the difference between res.send(), res.json(), res.end(), and res.render()?',
    hint: 'Format, headers, template compilation, and termination.',
    answer: 'res.send() sends general text/HTML (auto-detecting Content-Type). res.json() formats objects as JSON and sets application/json. res.end() terminates response without data. res.render() compiles and sends dynamic HTML templates.',
  },

  // ================= MONGODB & DATABASE MODELING (QUESTIONS 111–150) =================
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'wipro'],
    question: 'Explain the structural layout differences between standard text JSON and binary-encoded BSON data formats.',
    hint: 'Think about data types, parsing overhead, and storage size.',
    answer: 'JSON is plain text, supporting basic types (numbers, strings, arrays, objects). BSON is binary-encoded, supporting extra types (ObjectId, Date, Binary, RegExp) and is faster to traverse and parse.',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What is an embedded document (normalization) vs a referenced document (denormalization)? When do you choose each?',
    hint: 'Embedded nests objects; references link using ObjectIds.',
    answer: 'Embedded embeds child data in the parent document (good for 1-to-few, static data, fast reads). Referenced stores ObjectIds linking separate documents (good for 1-to-many, frequently updated data, avoiding duplication).',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'How do you design and execute advanced multi-stage data pipelines using MongoDB\'s Aggregation Framework ($match, $group, $lookup)?',
    hint: 'Pipeline filters, aggregates, and joins collections.',
    answer: 'Use aggregate(). Stages include: $match (filters records), $group (aggregates values, e.g. sums or averages), $project (reshapes fields), and $lookup (performs left outer joins with other collections).',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'infosys'],
    question: 'What is a Covered Query in MongoDB, and how does it eliminate the need to scan actual documents from disk storage?',
    hint: 'Lookups resolved entirely from index structures.',
    answer: 'A covered query is a query where all query filters and projections are resolved entirely from an index, without reading any actual documents. This completely avoids disk I/O, yielding massive performance gains.',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Medium',
    companies: ['zoho', 'cognizant'],
    question: 'Explain Mongoose middleware/hooks. Differentiate between pre-save validations and post-save logging actions.',
    hint: 'Intercepting model actions before or after saving.',
    answer: 'Hooks run during Mongoose execution. Pre-save hooks run before saving to hash passwords or validate values. Post-save hooks run after database write, ideal for notifications or logging operations.',
  },

  // ================= DATA ANALYST QUESTIONS =================
  {
    role: 'data',
    topic: 'SQL',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'infosys'],
    question: 'Explain the difference between WHERE and HAVING clauses. Provide an explicit query example.',
    hint: 'Compare row-level filtering vs group-level filtering.',
    answer: 'WHERE filters records before grouping (cannot reference aggregate functions). HAVING filters summarized groups after GROUP BY. Example: SELECT dept, AVG(sal) FROM emp WHERE sal > 1000 GROUP BY dept HAVING AVG(sal) > 5000;',
  },
  {
    role: 'data',
    topic: 'SQL',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro'],
    question: 'Describe all types of SQL Joins (INNER, LEFT, RIGHT, FULL OUTER) and how they process unmatched rows.',
    hint: 'Think about intersection, directional inclusion, and null values.',
    answer: 'INNER: returns matching rows in both tables. LEFT: returns all rows from left table + matched right rows. RIGHT: returns all rows from right table + matched left rows. FULL OUTER: returns all records if there is a match in left or right.',
  },
  {
    role: 'data',
    topic: 'SQL',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'What are Window Functions? Explain how ROW_NUMBER(), RANK(), and DENSE_RANK() assign ranks to rows.',
    hint: 'Think about ties/duplicates and gaps in rankings.',
    answer: 'Window functions compute over a set of rows. ROW_NUMBER() assigns consecutive integers (1,2,3). RANK() assigns same rank to duplicates, but skips numbers (e.g. 1, 2, 2, 4). DENSE_RANK() assigns same rank without gaps (e.g. 1, 2, 2, 3).',
  },
  {
    role: 'data',
    topic: 'SQL',
    difficulty: 'Easy',
    companies: ['cognizant', 'wipro', 'tcs'],
    question: 'What is the difference between the DROP, TRUNCATE, and DELETE commands in SQL?',
    hint: 'DDL vs DML, index/rollback implications, and row-by-row scans.',
    answer: 'DROP deletes table structure and data (DDL, cannot rollback). TRUNCATE removes all rows quickly by deallocating pages (DDL, cannot rollback). DELETE removes specific rows using WHERE (DML, logs triggers, supports rollback).',
  },
  {
    role: 'data',
    topic: 'Pandas',
    difficulty: 'Easy',
    companies: ['infosys', 'cognizant'],
    question: 'What are the primary differences between a Pandas Series object and a standard DataFrame structure?',
    hint: 'Dimensions, indexing, and tabular layout.',
    answer: 'A Series is a 1-dimensional labeled array (holds a single column/list). A DataFrame is a 2-dimensional tabular structure (like a spreadsheet/SQL table) holding rows and multiple Series columns sharing an index.',
  },
  {
    role: 'data',
    topic: 'Pandas',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain how the loc indexer differs from the iloc indexer when filtering rows and columns in Pandas.',
    hint: 'Label-based selection vs integer-based position selection.',
    answer: 'loc is label-based: select rows/columns using their index names or header labels. iloc is integer-position based: select rows/columns using their 0-indexed positions.',
  },
  {
    role: 'data',
    topic: 'Pandas',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain the execution differences between the map(), apply(), and applymap() functions in Pandas.',
    hint: 'Operations on Series, Dataframe columns, or element-wise values.',
    answer: 'map() is element-wise on a Series (maps values). apply() runs a function on axis (rows or columns of a DataFrame). applymap() runs a function element-wise on the entire DataFrame (deprecated in modern Pandas, replaced by map()).',
  },
  {
    role: 'data',
    topic: 'Statistics',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro'],
    question: 'Define the differences between Descriptive Statistics and Inferential Statistics.',
    hint: 'Summarizing actual data vs drawing conclusions about a population.',
    answer: 'Descriptive statistics summarizes/describes data features (e.g. mean, mode, standard deviation of a dataset). Inferential statistics makes predictions or generalizations about a larger population using sample data (e.g. t-tests, ANOVA).',
  },
  {
    role: 'data',
    topic: 'Statistics',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Explain Type I Error (False Positive) and Type II Error (False Negative). Provide a concrete scenario.',
    hint: 'Rejecting a true null hypothesis vs failing to reject a false null hypothesis.',
    answer: 'Type I Error: rejecting a true null hypothesis (e.g. declaring a healthy patient has a disease). Type II Error: failing to reject a false null hypothesis (e.g. declaring a sick patient is healthy).',
  },
  {
    role: 'data',
    topic: 'Statistics',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'What is a p-value? How do you interpret a p-value relative to a chosen significance level (alpha = 0.05)?',
    hint: 'Probability of observing test results under null hypothesis.',
    answer: 'The p-value is the probability of obtaining test results at least as extreme as the observed results, assuming the null hypothesis is true. If p-value < 0.05, we reject the null hypothesis; otherwise, we fail to reject it.',
  },

  // ================= JAVA DEVELOPER QUESTIONS =================
  {
    role: 'java',
    topic: 'Java Core',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro'],
    question: 'Why is Java called a platform-independent language? Explain the role of the JVM, JDK, and JRE.',
    hint: 'Bytecode execution, WORA concept, and compilation boundaries.',
    answer: 'Java compilation produces bytecode (WORA: Write Once, Run Anywhere). The JDK is development tools; the JRE is runtime environments; the JVM translates bytecode to machine code. The JVM itself is platform-dependent, but execute-ready bytecode runs on any JVM.',
  },
  {
    role: 'java',
    topic: 'Java Core',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'What is the difference between String, StringBuilder, and StringBuffer? Focus on mutability and thread safety.',
    hint: 'Strings are immutable; buffer has synchronized helpers.',
    answer: 'String is immutable (changes create new objects). StringBuilder is mutable and not thread-safe (faster, single-threaded). StringBuffer is mutable and thread-safe (slower due to synchronized helper methods).',
  },
  {
    role: 'java',
    topic: 'Java Core',
    difficulty: 'Medium',
    companies: ['cognizant', 'infosys'],
    question: 'What is the difference between an Interface and an Abstract Class? When should you use each in system design?',
    hint: 'Multiple inheritance support, state properties, default contracts.',
    answer: 'Abstract classes support instance state and can have non-public methods/constructors; classes extend one abstract class. Interfaces define stateless contracts; classes implement multiple interfaces. Use abstract classes for tight hierarchies; interfaces for shared traits.',
  },
  {
    role: 'java',
    topic: 'Java Core',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'infosys'],
    question: 'Explain Method Overloading vs Method Overriding. How does Java resolve them?',
    hint: 'Compile-time polymorphism vs runtime binding.',
    answer: 'Overloading: same method name, different parameters inside the same class (resolved at compile-time). Overriding: child class redefining parent method with same signature (resolved at runtime).',
  },
  {
    role: 'java',
    topic: 'Java Core',
    difficulty: 'Easy',
    companies: ['cognizant', 'wipro', 'tcs'],
    question: 'What is the purpose of the final keyword when applied to a variable, a method, and a class?',
    hint: 'Constants, prevention of overrides, and inheritance blocking.',
    answer: 'Final variable: makes it constant (value cannot change). Final method: prevents children from overriding it. Final class: prevents inheritance (cannot be subclassed).',
  },
  {
    role: 'java',
    topic: 'Collections',
    difficulty: 'Medium',
    companies: ['zoho', 'cognizant'],
    question: 'What is the difference between ArrayList and LinkedList regarding memory allocation and search speeds?',
    hint: 'Contiguous arrays vs linked node chains.',
    answer: 'ArrayList allocates contiguous memory; searches are O(1) by index, but modifications require shifting. LinkedList allocates non-contiguous nodes; searches require traversing sequential links, O(n), but modifications are O(1).',
  },
  {
    role: 'java',
    topic: 'Collections',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Explain the internal working mechanism of a HashMap (Buckets, Hash collisions, Linked Lists, Balanced Trees).',
    hint: 'Hashing, array buckets, collision list-to-tree conversion.',
    answer: 'HashMap uses key hashCode() to locate bucket index. In case of collisions, entries form linked lists. In Java 8+, if a bucket exceeds 8 entries and the map capacity is >= 64, it converts the list to a balanced Red-Black Tree to optimize search to O(log n).',
  },
  {
    role: 'java',
    topic: 'Collections',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain the difference between the start() method and the run() method of the Thread class.',
    hint: 'Thread spawning vs standard synchronous execution.',
    answer: 'start() spawns a new thread, allocates execution stacks, and calls the run() method asynchronously. run() simply executes code synchronously within the current thread as a normal method invocation.',
  },
  {
    role: 'java',
    topic: 'Spring Boot',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro', 'infosys'],
    question: 'What is the Spring Framework, and how does it define the concepts of Dependency Injection (DI) and Inversion of Control (IoC)?',
    hint: 'Object creation responsibility delegation and injection vectors.',
    answer: 'IoC delegates class instantiation and configuration to Spring containers. DI is the implementation; dependencies are injected into classes (via constructor or setter) rather than classes instantiating them directly, reducing tight coupling.',
  },
  {
    role: 'java',
    topic: 'Spring Boot',
    difficulty: 'Easy',
    companies: ['cognizant', 'infosys'],
    question: 'Explain the difference between @RestController and @Controller annotations in a Spring MVC web application.',
    hint: 'HTML template rendering vs JSON/XML API responses.',
    answer: '@Controller serves HTML views/templates, requiring @ResponseBody on methods to output raw data. @RestController is a shorthand combining @Controller and @ResponseBody, automatically serializing API return values as JSON.',
  },
  {
    role: 'java',
    topic: 'Spring Boot',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What is Spring Data JPA? Explain how it simplifies the data access layer using dynamic repository interfaces.',
    hint: 'Query derivation, boilerplate reduction, and hibernate abstractions.',
    answer: 'Spring Data JPA reduces DAO boilerplate. Developers define interfaces extending JpaRepository. Spring generates SQL dynamically based on method signatures (e.g. findByEmail) and manages session context automatically.',
  },

  // ================= PYTHON DEVELOPER QUESTIONS =================
  {
    role: 'python',
    topic: 'Python Basics',
    difficulty: 'Easy',
    companies: ['cognizant', 'infosys', 'tcs'],
    question: 'Explain Python\'s core data types. What is the fundamental difference between mutable types and immutable types?',
    hint: 'In-place updates vs reference changes for lists, tuples, and strings.',
    answer: 'Mutable types (lists, dicts, sets) can modify their contents in-place. Immutable types (strings, tuples, ints) cannot be changed; modifying them creates a new object in memory with a new reference address.',
  },
  {
    role: 'python',
    topic: 'Python Basics',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What is the Global Interpreter Lock (GIL) in Python, and how does it affect multi-threaded execution patterns for CPU-bound tasks?',
    hint: 'Thread lock preventing concurrent python bytecode execution.',
    answer: 'The GIL is a mutex preventing multiple threads from executing Python bytecodes concurrently. This makes multi-threaded CPU-bound programs single-core. To achieve parallelism, use the multiprocessing module or async IO for I/O-bound tasks.',
  },
  {
    role: 'python',
    topic: 'Decorators',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Explain Python Decorators. How do you create a custom decorator that accepts arguments and logs function execution times?',
    hint: 'Nested wrapper functions returning modified closures.',
    answer: 'A decorator wraps another function. If the decorator accepts arguments, it needs three levels of nested functions: the outer handles decorator arguments, the middle receives the target function, and the inner wraps call execution.',
  },
  {
    role: 'python',
    topic: 'Python Basics',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'What is the difference between a Generator and a standard Iterator? How does the yield keyword save memory during execution?',
    hint: 'Sequence materialization vs stateful pagination.',
    answer: 'Iterators use custom classes with __iter__ and __next__. Generators are functions that return values dynamically using yield. yield freezes execution state, returning items one-by-one without materializing the whole list in memory.',
  },
  {
    role: 'python',
    topic: 'Python Basics',
    difficulty: 'Easy',
    companies: ['tcs', 'wipro'],
    question: 'Explain the utility of Python\'s *args and **kwargs magic variables inside a flexible function definition.',
    hint: 'Variable length arguments mapping to tuples and dictionaries.',
    answer: '*args catches positional arguments as a tuple. **kwargs catches keyword arguments as a dictionary. They permit calling functions with arbitrary parameter configurations.',
  },
  {
    role: 'python',
    topic: 'Django & FastAPI',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What is the Django ORM? How do you optimize database queries to avoid the N+1 query trap using select_related and prefetch_related?',
    hint: 'Compare single SQL JOIN vs multiple queries in memory.',
    answer: 'N+1 is triggered when parent queries trigger individual sub-queries for child relationships. select_related uses SQL JOIN (good for foreign keys/one-to-one). prefetch_related queries children as a batch and joins them in Python (good for many-to-many).',
  },
  {
    role: 'python',
    topic: 'Django & FastAPI',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'What is the difference between standard synchronous route handlers (def) and asynchronous handlers (async def) inside FastAPI?',
    hint: 'Concurrency support, worker blocking, and event loops.',
    answer: 'async def routes run in the event loop without blocking thread pools, ideal for I/O bound operations. def routes run in a separate thread pool, preventing CPU-intensive or non-async code from freezing the entire system loop.',
  },
  {
    role: 'python',
    topic: 'Machine Learning',
    difficulty: 'Easy',
    companies: ['cognizant', 'infosys'],
    question: 'What are the primary differences between NumPy arrays and standard Python lists concerning memory allocation and computation speeds?',
    hint: 'Contiguous arrays with single types vs arrays of pointers to arbitrary objects.',
    answer: 'Python lists are arrays of pointers pointing to scattered object values in memory, which allows mixed types but lacks caching. NumPy arrays allocate contiguous blocks of memory holding a single data type, utilizing vectorization.',
  },
  {
    role: 'python',
    topic: 'Machine Learning',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Explain the concepts of Overfitting and Underfitting. How do you spot them using training and validation loss curves?',
    hint: 'Training metrics improving while validation metrics degrade.',
    answer: 'Underfitting occurs when the model is too simple (high training and validation loss). Overfitting occurs when the model memorizes noise; training loss keeps declining, but validation loss flatlines or begins to climb.',
  },

  // ================= HR & BEHAVIORAL QUESTIONS =================
  {
    role: 'hr',
    topic: 'Introduction',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Tell me about yourself. Walk me through your academic background and key project achievements.',
    hint: 'Pitch your journey in a minute: education, core projects, skills, and values.',
    answer: 'Start with current status (education/graduation), cover 1-2 major technical projects highlighting your role and stacks, list core developer strengths, and align your goals with the company.',
  },
  {
    role: 'hr',
    topic: 'Motivation',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Why do you want to join our organization? What aspects of our corporate culture and scale appeal to you?',
    hint: 'Mention client scale, upskilling opportunities, or product philosophies.',
    answer: 'Customize based on target company: e.g., for Zoho, mention bootstrap independence and product design ownership. For TCS/Infosys, discuss global scaling, training bootcamps, and client diversity.',
  },
  {
    role: 'hr',
    topic: 'Self-Awareness',
    difficulty: 'Medium',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'What are your greatest professional strengths, and what do you consider your biggest weakness?',
    hint: 'Strength with a quick example; weakness with an active improvement strategy.',
    answer: 'Choose a relevant strength (e.g. adaptability, structured debugging) and provide a quick story. For weakness, list a genuine non-critical skill (e.g. stage presentation) and show how you are proactively training to fix it.',
  },
  {
    role: 'hr',
    topic: 'Career Goals',
    difficulty: 'Medium',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Where do you see yourself in five years? How does a career path within this company align with that vision?',
    hint: 'Mention engineering depth, ownership, and collaborative leadership.',
    answer: 'Express goals to master system architectures, take ownership of product modules, lead collaborative projects, and grow alongside the organization\'s technological needs.',
  },
  {
    role: 'hr',
    topic: 'Behavioral',
    difficulty: 'Medium',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Can you describe a situation where you had to work with a teammate who disagreed with your approach? How did you align?',
    hint: 'Focus on communication, objective metrics, and compromise.',
    answer: 'Use STAR format: Describe a project disagreement, show how you scheduled a 1-on-1 to review options objectively based on performance or deadlines, and detail how you compromised to complete the task successfully.',
  },
  {
    role: 'hr',
    topic: 'Behavioral',
    difficulty: 'Medium',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'How do you handle high-pressure environments, tight project deadlines, or sudden shifts in client requirements?',
    hint: 'Describe prioritization, scope management, and professional composure.',
    answer: 'Discuss prioritizing tasks (e.g. using Eisenhower Matrix), breaking down blocks into atomic sub-tasks, communicating transparently with coordinators, and maintaining a calm, iterative approach to debugging.',
  },

  // ================= APTITUDE QUESTIONS =================
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Medium',
    companies: ['tcs'],
    question: 'A train passes a standing pole in 12 seconds and crosses a 300-meter long platform in 27 seconds. Calculate the speed of the train in km/hr.',
    hint: 'Speed = Platform Length / Time difference to cross platform.',
    answer: 'Speed = 300m / (27s - 12s) = 20 m/s. Convert to km/hr: 20 * 18/5 = 72 km/hr.',
  },
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Easy',
    companies: ['zoho'],
    question: 'If 7 cats can catch 7 mice in exactly 7 minutes, how many minutes will it take 100 cats to catch 100 mice?',
    hint: 'Rate remains constant; one cat catches one mouse in 7 minutes.',
    answer: 'It takes 7 minutes. Since 7 cats catch 7 mice in 7 minutes, it means 1 cat catches 1 mouse in 7 minutes. Therefore, 100 cats will catch 100 mice in the same 7 minutes.',
  },
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Easy',
    companies: ['infosys'],
    question: 'Find the missing value in the sequence pattern: 3, 5, 9, 17, 33, (__).',
    hint: 'Look at the difference between consecutive numbers: +2, +4, +8, +16...',
    answer: 'The next difference is +32. So, 33 + 32 = 65.',
  },
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Medium',
    companies: ['wipro'],
    question: 'A sum of ₹3,000 becomes ₹6,000 in 5 years when invested at a constant rate of compound interest. What will the total amount be at the end of 15 years?',
    hint: 'The sum doubles every 5 years.',
    answer: 'At 5 years: ₹6,000. At 10 years: ₹12,000. At 15 years: ₹24,000.',
  },
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Medium',
    companies: ['cognizant'],
    question: 'A container holds a mixture of syrup and water in the ratio 5:2. If 6 liters of water are added, the ratio shifts to 5:4. Find the initial volume of syrup.',
    hint: 'The volume of syrup remains constant.',
    answer: 'Let syrup = 5x, water = 2x. Adding 6L water makes it 5x / (2x + 6) = 5/4. Solves to x = 3. Initial syrup = 5 * 3 = 15 liters.',
  },
  {
    role: 'aptitude',
    topic: 'Aptitude',
    difficulty: 'Easy',
    companies: ['freshworks'],
    question: 'A customer support center resolves 80% of incoming tickets on the first contact. If they receive 1,200 tickets daily, how many require secondary escalation steps?',
    hint: 'Find 20% of 1,200.',
    answer: 'Escalated tickets = 20% of 1,200 = 0.2 * 1,200 = 240 tickets.',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Easy',
    companies: ['zoho', 'tcs', 'freshworks'],
    question: 'Reverse a Linked List: Given the head of a singly linked list, reverse the list, and return the reversed list.',
    hint: 'Use three pointers: prev, curr, and next.',
    answer: 'Iterative solution: Initialize prev as null, curr as head. In a loop, store next = curr.next, update curr.next = prev, move prev = curr, and curr = next. Return prev.',
    externalLink: 'https://leetcode.com/problems/reverse-linked-list/',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'cognizant'],
    question: 'Two Sum: Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
    hint: 'Use a hash map to store elements and their indices for O(n) lookup.',
    answer: 'Create an empty Map. Iterate through the array. For each number, calculate difference = target - num. If difference is in the Map, return [Map.get(difference), current_index]. Otherwise, store the number and its index in the Map.',
    externalLink: 'https://leetcode.com/problems/two-sum/',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Easy',
    companies: ['wipro', 'cognizant', 'zoho'],
    question: 'Valid Parentheses: Given a string s containing just the characters parentheses, brackets and curly braces, determine if the input string is valid.',
    hint: 'Use a stack to keep track of opening brackets.',
    answer: 'Initialize an empty stack. Loop through each character. If it is an opening bracket, push it onto the stack. If it is a closing bracket, pop from the stack and check if it matches the opening bracket. If stack is empty at the end, return true.',
    externalLink: 'https://leetcode.com/problems/valid-parentheses/',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho'],
    question: 'Longest Substring Without Repeating Characters: Given a string s, find the length of the longest substring without repeating characters.',
    hint: 'Use a sliding window approach with a Set/Map.',
    answer: 'Maintain a sliding window with left and right pointers. Add characters to a Set. If a duplicate is found, shrink the window from the left until the duplicate is removed. Track max window size.',
    externalLink: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Merge Intervals: Given an array of intervals where intervals[i] = [start_i, end_i], merge all overlapping intervals.',
    hint: 'Sort the intervals by their start times first.',
    answer: 'Sort intervals by start. Iterate through them. If the current interval overlaps with the last merged interval (current start <= last end), merge them by updating the last end. Otherwise, append the current interval.',
    externalLink: 'https://leetcode.com/problems/merge-intervals/',
  },
  {
    role: 'dsa',
    topic: 'DSA',
    difficulty: 'Hard',
    companies: ['freshworks', 'tcs', 'infosys'],
    question: 'Search in Rotated Sorted Array: Given a rotated sorted array and a target, return the index of the target if it is in the array, or -1 otherwise.',
    hint: 'Modify binary search to find which half of the array is sorted.',
    answer: 'Run binary search. Find mid. Determine if left half (low to mid) is sorted. If so, check if target falls within left range. Otherwise, target must be in the right half. Apply same logic recursively.',
    externalLink: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
  },
];
