export const questions = [
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'tcs'],
    question: 'Explain the Virtual DOM in React and how it improves performance.',
    hint: 'Talk about diffing, reconciliation, and selective DOM updates.',
    answer: 'The Virtual DOM is an in-memory representation of the UI. React compares new and previous trees, computes the minimal changes, and updates the real DOM efficiently.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'wipro'],
    question: 'What is middleware in Express.js? Give a real-world use case.',
    hint: 'Think about authentication, logging, validation, and error handling.',
    answer: 'Middleware is a function that runs during the request-response cycle. It can inspect or modify req/res, end the response, or call next().',
  },
  {
    role: 'mern',
    topic: 'Auth',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'How does JWT authentication work? Explain the full flow.',
    hint: 'Cover token creation, signing, storage, sending, and verification.',
    answer: 'After login, the server signs a token containing user claims. The client sends it in Authorization headers. Protected routes verify the signature before granting access.',
  },
  {
    role: 'mern',
    topic: 'MongoDB',
    difficulty: 'Easy',
    companies: ['cognizant', 'tcs', 'wipro'],
    question: 'What is the difference between SQL and NoSQL? When would you choose MongoDB?',
    hint: 'Compare schema design, joins, document shape, and scaling.',
    answer: 'SQL is relational and schema-first. MongoDB stores flexible JSON-like documents and is useful when data shape evolves quickly or maps naturally to documents.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks'],
    question: 'Explain useEffect cleanup function with an example.',
    hint: 'Think about subscriptions, timers, and event listeners.',
    answer: 'A cleanup function runs before an effect re-runs or the component unmounts. It prevents leaks by clearing intervals, aborting requests, or removing listeners.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Hard',
    companies: ['zoho', 'freshworks', 'infosys'],
    question: 'Explain the event loop in Node.js.',
    hint: 'Mention call stack, microtasks, timers, poll, and callbacks.',
    answer: 'The event loop lets Node handle async work without blocking. It processes phases like timers, poll, and check, while microtasks run between phases.',
  },
  {
    role: 'mern',
    topic: 'React',
    difficulty: 'Hard',
    companies: ['freshworks', 'zoho'],
    question: 'What is Redux and when should you use it over Context API?',
    hint: 'Consider app scale, complexity, devtools, and performance.',
    answer: 'Redux centralizes state with predictable updates. Use it for large apps with complex shared state; Context API suits simpler prop-drilling cases.',
  },
  {
    role: 'mern',
    topic: 'Node.js',
    difficulty: 'Easy',
    companies: ['tcs', 'cognizant', 'wipro', 'infosys'],
    question: 'How do you handle CORS in a Node.js/Express backend?',
    hint: 'Mention the cors npm package and manual headers.',
    answer: 'Use the cors middleware or set Access-Control-Allow-Origin headers to permit cross-origin requests from trusted frontend origins.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Easy',
    companies: ['zoho', 'tcs', 'amazon'],
    question: 'Find the middle element of a Linked List.',
    hint: 'Use the fast and slow pointer (Tortoise and Hare) approach.',
    practiceUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/',
    answer: 'Use two pointers. Fast moves two steps, Slow moves one. When Fast reaches the end, Slow is at the middle.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Medium',
    companies: ['amazon', 'freshworks', 'zoho'],
    question: 'Implement a Stack using Queues.',
    hint: 'You can use two queues or one queue with rotation.',
    practiceUrl: 'https://leetcode.com/problems/implement-stack-using-queues/',
    answer: 'Can be done using two queues by making push operation costly or pop operation costly.',
  },
  {
    role: 'mern',
    topic: 'DSA',
    difficulty: 'Hard',
    companies: ['amazon', 'zoho'],
    question: 'Lowest Common Ancestor of a Binary Tree.',
    hint: 'Use recursion: if current node is one of the targets, it could be LCA.',
    practiceUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
    answer: 'Recurse left and right. If both return non-null, current node is LCA. If one is null, return the other.',
  },
  {
    role: 'hr',
    topic: 'Introduction',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'zoho', 'freshworks'],
    question: 'Tell me about yourself.',
    hint: 'Keep it around 90 seconds: education, skills, projects, and role fit.',
    answer: 'A strong fresher answer connects education, technical skills, projects, and why the target role is a good fit.',
  },
  {
    role: 'hr',
    topic: 'Motivation',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'cognizant', 'wipro'],
    question: 'Why do you want to join this company?',
    hint: 'Research the company. Mention specific product, values, and growth.',
    answer: 'Connect your skills and goals with the company mission, culture, and learning opportunities.',
  },
  {
    role: 'hr',
    topic: 'Behavioral',
    difficulty: 'Medium',
    companies: ['freshworks', 'zoho', 'infosys'],
    question: 'Describe a challenging project and how you handled it.',
    hint: 'Use STAR: Situation, Task, Action, Result.',
    answer: 'Use a structured story with the problem, your responsibility, actions, trade-offs, and measurable result.',
  },
  {
    role: 'hr',
    topic: 'Career Goals',
    difficulty: 'Medium',
    companies: ['tcs', 'wipro', 'cognizant'],
    question: 'Where do you see yourself in 5 years?',
    hint: 'Show ambition and alignment with the company trajectory.',
    answer: 'Describe growth in technical depth, ownership, and contribution to team or product outcomes.',
  },
  {
    role: 'java',
    topic: 'Core Java',
    difficulty: 'Easy',
    companies: ['tcs', 'infosys', 'wipro', 'cognizant', 'hcl', 'accenture'],
    question: 'What is the platform independence of Java and how is it achieved?',
    hint: 'Think about Bytecode and the JVM.',
    answer: 'Java is platform-independent because of Bytecode. The same .class file can run on any OS as long as it has a compatible JVM.',
  },
  {
    role: 'java',
    topic: 'Collections',
    difficulty: 'Medium',
    companies: ['zoho', 'freshworks', 'amazon', 'flipkart'],
    question: 'Difference between ArrayList and LinkedList in Java.',
    hint: 'Consider search vs insertion/deletion performance.',
    answer: 'ArrayList is better for random access (O(1)). LinkedList is better for frequent insertions/deletions at the beginning or middle (O(1) if you have the node).',
  },
  {
    role: 'java',
    topic: 'Spring Boot',
    difficulty: 'Hard',
    companies: ['freshworks', 'chargebee'],
    question: 'How does Dependency Injection work in Spring Boot?',
    hint: 'Think about @Autowired, Bean definitions, and IoC container.',
    answer: 'DI is a design pattern where the container provides dependencies to objects. Spring uses the IoC container to manage bean lifecycles and inject them.',
  },
  {
    role: 'python',
    topic: 'Basics',
    difficulty: 'Easy',
    companies: ['cognizant', 'hcl', 'tcs', 'wipro'],
    question: 'What is the difference between a list and a tuple in Python?',
    hint: 'Think about mutability.',
    answer: 'Lists are mutable (can be changed), while tuples are immutable (fixed size/content).',
  },
  {
    role: 'python',
    topic: 'Advanced',
    difficulty: 'Medium',
    companies: ['accenture', 'mphasis', 'infosys', 'tcs'],
    question: 'Explain Python Decorators with a use case.',
    hint: 'Think about extending function behavior without modifying it.',
    answer: 'Decorators are functions that take another function as an argument and extend its behavior. Used for logging, authentication, etc.',
  },
  {
    role: 'python',
    topic: 'Frameworks',
    difficulty: 'Hard',
    companies: ['mindtree', 'amazon', 'freshworks', 'zoho'],
    question: 'What is GIL (Global Interpreter Lock) in Python?',
    hint: 'Consider multi-threading vs multi-processing.',
    answer: 'GIL is a mutex that protects access to Python objects, preventing multiple threads from executing Python bytecodes at once.',
  },
  {
    role: 'frontend',
    topic: 'CSS',
    difficulty: 'Easy',
    companies: ['zoho', 'freshworks', 'swiggy'],
    question: 'Explain the CSS Box Model.',
    hint: 'Think about Content, Padding, Border, Margin.',
    answer: 'The Box Model describes the rectangular boxes generated for elements. It consists of Content, Padding, Border, and Margin in that order.',
  },
  {
    role: 'frontend',
    topic: 'JavaScript',
    difficulty: 'Medium',
    companies: ['flipkart', 'urban company'],
    question: 'What is a Closure in JavaScript?',
    hint: 'A function having access to its parent scope even after parental execution.',
    answer: 'A closure is a combination of a function bundled together with references to its surrounding state (lexical environment).',
  },
  {
    role: 'data',
    topic: 'SQL',
    difficulty: 'Easy',
    companies: ['mu sigma', 'fractal', 'accenture', 'tcs', 'infosys'],
    question: 'Difference between INNER JOIN and LEFT JOIN in SQL.',
    hint: 'Consider what happens when there is no match in the right table.',
    answer: 'INNER JOIN returns only matching rows. LEFT JOIN returns all rows from the left table and matching rows from the right table.',
  },
  {
    role: 'data',
    topic: 'Statistics',
    difficulty: 'Medium',
    companies: ['tiger analytics', 'mu sigma', 'wipro', 'cognizant'],
    question: 'What is a P-value in hypothesis testing?',
    hint: 'Strong evidence against the null hypothesis.',
    answer: 'The p-value is the probability of obtaining test results at least as extreme as the results actually observed, under the assumption that the null hypothesis is correct.',
  },
];
